networks:
  ciancinetwork:
    external: true
services:
  web:
    build: .
    container_name: nginx_proxy
    extra_hosts:
    - localhost:host-gateway
    - host.docker.internal:host-gateway
    - kubernetes.docker.internal:host-gateway
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test:
      - CMD-SHELL
      - curl --fail http://dev.marcocianci.com:80 && curl --insecure --fail https://dev.marcocianci.com:443
      timeout: 30s
    image: nginx:latest
    networks:
    - ciancinetwork
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./certs:/etc/nginx/ssl:ro
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    working_dir: /etc/nginx
version: '3.9'
